name: Upwork-Sniper-8min

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  run-sniper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install feedparser requests pyarmor

      - name: Run Sniper
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          MY_RSS: ${{ secrets.MY_RSS }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
          PYTHONPATH: ${{ github.workspace }}
        run: python main.py
