name: Upwork-Sniper-8min

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  run-sniper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Sniper
        run: python main.py
